project:
  type: website
  output-dir: docs

website:
  title: "Math 3376 Simpsons Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Packages Required.qmd
        text: Packages Required
      - href: Simpsons Data.qmd
        text: Data Preparation
      - href: Exploratory Data.qmd
        text: Exploratory Data Analysis
      - href: Summary.qmd
        text: Summary
format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

