project:
  type: website
  output-dir: docs

website:
  title: "3376project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Packages Required.qmd
        text: Packages Required
      - href: Simpsons Data.qmd
        text: Data Preparation
      - href: Exploratory Data.qmd
        text: Exploratory Data Analysis
      - href: Summary.qmd
        text: Summary
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

